### ISSUE TITLE
Django Patterns module

### ISSUE THREAD

**Issue by tubia** [pat1/autoradio#12]
Starting from Django 1.8 the Patterns module has been deprecated. From Django 1.10 has been removed.
So, with Django 1.10 when you try to start autoradioweb with `./autoradioweb run` an error related to `urlpatterns` is returned.
Commenting [line 3](https://github.com/pat1/autoradio/blob/master/autoradio/doc/urls.py#L3) from `autoradio/autoradio/doc/urls.py` fix this error.
See the pull request #13

**Comment by pat1** [comment]
pull request merged and tested
