### ISSUE TITLE
Player autoradio

### ISSUE THREAD

**Issue by amanfredini** [pat1/autoradio#26]
Error getting player status...
Run autoradiod or verify setting..

**Comment by eineki** [comment]
It is a mis-configuration. Please provide us with further explanation on when the issue arise, at the state the request is useless (see http://stackoverflow.com/help/how-to-ask)

In the meantime send me a mail if you are in trouble.

**Comment by amanfredini** [comment]
When i start autoplayerd,the message are...
Failed to connect to socket: localhost:1234... Connection refused

**Comment by pat1** [comment]
do you have installed a package (debian/ubuntu) or do you try to start from a cloned git repo ?
Which version do you use? 

Have you read the easy install hoto?
https://github.com/pat1/autoradio/blob/master/README#L116

The message come from a mis-configuration or from a system installation without the right daemons running.

**Comment by amanfredini** [comment]
Version 2.8.6... How can i start from a cloned repo?
